export const UPDATEUSERLOCATION = 'UPDATEUSERLOCATION';
export const UPDATECENTERLOCATION = 'UPDATECENTERLOCATION';
export const UPDATESEARCHSTATUS = 'UPDATESEARCHSTATUS'
export const REGISTER = 'REGISTER';
export const LIST_FETCHED = 'LIST_FETCHED';
