export const UPDATEUSERLOCATION = 'UPDATEUSERLOCATION';
export const UPDATECENTERLOCATION = 'UPDATECENTERLOCATION';
export const UPDATESEARCHSTATUS = 'UPDATESEARCHSTATUS'
export const REGISTER = 'REGISTER';
export const STORE_TOKEN = 'STORETOKEN';
export const SESSION_OK = 'SESSIONOK';
export const LOGIN='LOGIN';
